"""Train CIFAR10-DVS SNN baseline for HIPSA.

This script is intentionally tied to the split generated by pre_cifar10dvs.py.
It does not create a new split during training, which keeps eval00-03 aligned
with the trained checkpoint.

Run from project root:
  python train/pre_cifar10dvs.py --config configs/config_cifar10dvs.yaml
  python train/train_cifar10dvs.py --config configs/config_cifar10dvs.yaml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Dict

from tqdm import tqdm

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import torch
from torch.utils.data import Subset

from spikingjelly.datasets.cifar10_dvs import CIFAR10DVS

from models.model_registry import build_model, describe_model
from train.train_utils import (
    append_csv_row,
    build_criterion,
    build_loader,
    build_optimizer,
    build_scheduler,
    choose_device,
    create_run_dir,
    evaluate,
    get_grad_scaler,
    load_config,
    load_model_weights,
    load_split,
    save_checkpoint,
    save_json,
    set_seed,
    train_one_epoch,
)

try:
    from utils.logger import logger
except Exception:  # pragma: no cover
    from train.train_utils import logger


def build_dataset(config: Dict[str, Any]) -> CIFAR10DVS:
    ds_cfg = config["dataset"]
    return CIFAR10DVS(
        root=config["paths"]["dataset_root"],
        data_type=ds_cfg.get("data_type", "frame"),
        frames_number=int(ds_cfg["time_steps"]),
        split_by=ds_cfg.get("split_by", "number"),
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Train CIFAR10-DVS SNN baseline.")
    parser.add_argument("--config", type=str, default="configs/config_cifar10dvs.yaml")
    parser.add_argument("--device", type=str, default="auto")
    parser.add_argument("--resume", type=str, default=None, help="Optional checkpoint to resume/evaluate weights from.")
    parser.add_argument("--eval-only", action="store_true", help="Only evaluate the given/best checkpoint.")
    args = parser.parse_args()

    config = load_config(args.config)
    exp = config.get("experiment", {})
    set_seed(int(exp.get("seed", 42)), bool(exp.get("deterministic", True)), bool(exp.get("benchmark", False)))
    device = choose_device(args.device)

    if device.type == "cuda":
        torch.backends.cudnn.benchmark = bool(config["experiment"].get("benchmark", True))
        torch.backends.cudnn.deterministic = bool(config["experiment"].get("deterministic", False))
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True

        try:
            torch.set_float32_matmul_precision("high")
        except Exception:
            pass

    split_file = Path(config["split"]["split_file"])
    if not split_file.exists():
        raise FileNotFoundError(f"Split file not found: {split_file}. Run train/pre_cifar10dvs.py first.")
    split = load_split(split_file)

    dataset = build_dataset(config)
    train_ds = Subset(dataset, split["train_indices"])
    val_ds = Subset(dataset, split["val_indices"])
    test_ds = Subset(dataset, split["test_indices"])

    tr = config["training"]
    train_loader = build_loader(
        train_ds,
        batch_size=int(tr["batch_size_train"]),
        shuffle=True,
        config=config,
        drop_last=bool(tr.get("train_drop_last", True)),
    )
    val_loader = build_loader(
        val_ds,
        batch_size=int(tr["batch_size_eval"]),
        shuffle=False,
        config=config,
        drop_last=bool(tr.get("eval_drop_last", False)),
    )
    test_loader = build_loader(
        test_ds,
        batch_size=int(tr["batch_size_eval"]),
        shuffle=False,
        config=config,
        drop_last=bool(tr.get("eval_drop_last", False)),
    )

    run_dir = create_run_dir(config, args.config, "cifar10dvs")
    save_json({"split_file": str(split_file), "split_summary": {
        "train": len(train_ds), "val": len(val_ds), "test": len(test_ds)
    }}, run_dir / "metrics" / "split_used.json")

    model = build_model(config).to(device)
    tqdm.write("=== CIFAR10-DVS training ===")
    tqdm.write(f"Run dir: {run_dir}")
    tqdm.write(f"Device: {device}")
    tqdm.write(f"Model: {describe_model(model)}")
    tqdm.write(f"Train/Val/Test samples: {len(train_ds)} / {len(val_ds)} / {len(test_ds)}")

    logger.info("=== CIFAR10-DVS training ===")
    logger.info(f"Run dir: {run_dir}")
    logger.info(f"Device: {device}")
    logger.info(f"Model: {describe_model(model)}")
    logger.info(f"Train/Val/Test samples: {len(train_ds)} / {len(val_ds)} / {len(test_ds)}")

    optimizer = build_optimizer(model, config)
    scheduler = build_scheduler(optimizer, config)
    criterion = build_criterion(config)
    scaler = get_grad_scaler(bool(tr.get("amp", False)))

    if args.resume:
        tqdm.write(f"Loading checkpoint: {args.resume}")
        logger.info(f"Loading checkpoint: {args.resume}")
        load_model_weights(model, args.resume, device)

    if args.eval_only:
        ckpt = args.resume or str(run_dir / "checkpoints" / "best_val.pth")
        load_model_weights(model, ckpt, device)
        test_metrics = evaluate(model, test_loader, criterion, config, device, desc="Test")
        tqdm.write(f"Eval-only test metrics: {test_metrics}")
        logger.info(f"Eval-only test metrics: {test_metrics}")
        save_json(test_metrics, run_dir / "metrics" / "eval_only_test.json")
        return

    best_val = -1.0
    best_epoch = -1
    epochs = int(tr["epochs"])
    save_interval = int(tr.get("checkpoint", {}).get("save_interval_epochs", 10))
    train_log = run_dir / "metrics" / "train_log.csv"

    for epoch in range(1, epochs + 1):
        train_metrics = train_one_epoch(model, train_loader, optimizer, criterion, config, device, scaler, epoch)
        val_metrics = evaluate(model, val_loader, criterion, config, device, desc=f"Val {epoch}")
        if scheduler is not None:
            scheduler.step()

        lr = float(optimizer.param_groups[0]["lr"])
        row = {
            "epoch": epoch,
            "lr": lr,
            "train_loss": train_metrics["loss"],
            "train_acc": train_metrics["acc"],
            "val_loss": val_metrics["loss"],
            "val_acc": val_metrics["acc"],
        }
        append_csv_row(train_log, row)
        msg = (
            f"Epoch {epoch:03d}/{epochs} | LR {lr:.6g} | "
            f"Train {train_metrics['acc']:.2f}% loss {train_metrics['loss']:.4f} | "
            f"Val {val_metrics['acc']:.2f}% loss {val_metrics['loss']:.4f}"
        )

        tqdm.write(msg)
        logger.info(msg)


        save_checkpoint(run_dir / "checkpoints" / "last.pth", model, optimizer, scheduler, epoch, {"train": train_metrics, "val": val_metrics}, config)
        if epoch % save_interval == 0:
            save_checkpoint(run_dir / "checkpoints" / f"epoch_{epoch:03d}.pth", model, optimizer, scheduler, epoch, {"train": train_metrics, "val": val_metrics}, config)

        if val_metrics["acc"] > best_val:
            best_val = float(val_metrics["acc"])
            best_epoch = epoch
            save_checkpoint(run_dir / "checkpoints" / "best_val.pth", model, optimizer, scheduler, epoch, {"train": train_metrics, "val": val_metrics}, config)
            logger.info(f"New best val checkpoint: epoch {epoch}, val_acc={best_val:.2f}%")

    # Final test is run once using best validation checkpoint.
    best_path = run_dir / "checkpoints" / "best_val.pth"
    load_model_weights(model, best_path, device)
    test_metrics = evaluate(model, test_loader, criterion, config, device, desc="Final Test")
    final = {"best_epoch": best_epoch, "best_val_acc": best_val, "test": test_metrics, "run_dir": str(run_dir)}
    save_json(final, run_dir / "metrics" / "final_test.json")
    tqdm.write(f"Final test with best-val checkpoint: {test_metrics}")
    tqdm.write("=== CIFAR10-DVS training complete ===")

    logger.info(f"Final test with best-val checkpoint: {test_metrics}")
    logger.info("=== CIFAR10-DVS training complete ===")


if __name__ == "__main__":
    main()
